name = "IFXFiles"
uuid = "e775d6fb-5ddd-48fe-9baf-3c1128b88c84"
version = "1.0.0-DEV"
authors = ["Kamran Melikov <melikovk@gmail.com> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
